### ISSUE TITLE
Body Lenght is not the good value

### ISSUE THREAD

**Issue by goldorack34** [alicommit-malp/Dotnet-Core-Request-Body-Peeker#1]
// I put 14072 in the Header Content-Length. I used PostMan and in the raw body i pasted a big XML
// Used notepad++ to get the Lenght gives me 14072

int bodyLength = Int32.Parse(Request.Headers["Content-Length"].ToString());

// I use this 
Request.HttpContext.Request.PeekBody().Length; // returns 14059

// If i copy the content of Request.HttpContext.Request.PeekBody.ToString() in notepad++ i get 14072 too. Why PeekBody.Length() dosent give me the same?

**Comment by alicommit-malp** [comment]
This issue can ben because of the different formatting and/or encoding of the notepad++ , 

please give a try to the new version with you can change the default [encodings](https://github.com/alicommit-malp/Dotnet-Core-Request-Body-Peeker/blob/master/test/Request.Body.Peeker.Test/PeekWithEncodingTests.cs)

` var peekBody = await _httpContext.Request.PeekBodyAsync(new UTF8Encoding());`

**Comment by goldorack34** [comment]
The new version works very well i got the good length now. Very appreciated.
